#!/bin/sh

failed=0
check () {
    command="$1"
    expected="$2"
    result=`$command`
    echo -n "testing $command ... "
    if [ "$result" != "$expected" ]; then
        echo "failed:"
        echo "  Expected: $expected"
        echo "  Got: $result"
        failed=1
    else
        echo "ok"
    fi
}

check "cargo run --bin lrcalc -- lrcoef 3,2,1 2,1 2,1" "2"

check "cargo run --bin lrcalc -- skew 3,2,1 2,1" "2  (2,1)
1  (1,1,1)
1  (3)"

check "cargo run --bin lrcalc -- skew -m 3,2,1 2,1" "0+2*s[2,1]+1*s[1,1,1]+1*s[3]"

check "cargo run --bin lrcalc -- skew -r 2 3,2,1 2,1" "2  (2,1)
1  (3)"

check "cargo run --bin lrcalc -- skew -m -r 2 3,2,1 2,1" "0+2*s[2,1]+1*s[3]"

check "cargo run --bin lrcalc -- mult 2,1 2,1" "2  (3,2,1)
1  (4,2)
1  (3,1,1,1)
1  (3,3)
1  (2,2,1,1)
1  (2,2,2)
1  (4,1,1)"

check "cargo run --bin lrcalc -- mult -m 2,1 2,1" "0+2*s[3,2,1]+1*s[4,2]+1*s[3,1,1,1]+1*s[3,3]+1*s[2,2,1,1]+1*s[2,2,2]+1*s[4,1,1]"

check "cargo run --bin lrcalc -- mult -f -r 3 -c 2 3,2,1 3,2,1" "1  (4,4,4)
1  (5,4,3)"

check "cargo run --bin lrcalc -- mult -m -f -r 3 -c 2 3,2,1 3,2,1" "0+1*s[4,4,4]+1*s[5,4,3]"

check "cargo run --bin lrcalc -- mult -q -r 3 -c 2 3,2,1 3,2,1" "1  (2)
1  (1,1)"

check "cargo run --bin lrcalc -- mult -m -q -r 3 -c 2 3,2,1 3,2,1" "0+1*q^2*s[2]+1*q^2*s[1,1]"

check "cargo run --bin lrcalc -- coprod 3,2,1" "1  (2,1,1)  (1,1)
1  (3,2,1)  ()
1  (3,1,1)  (1)
1  (2,2)  (1,1)
2  (2,1)  (2,1)
1  (3,2)  (1)
1  (3,1)  (2)
1  (1,1,1)  (2,1)
1  (2,2,1)  (1)
1  (2,1,1)  (2)
1  (2,2)  (2)
1  (2,1)  (3)
1  (3,1)  (1,1)"

check "cargo run --bin schubmult -- 1,3,2 1,3,2" "1  (2,3,1)
1  (1,4,2,3)"

check "cargo run --bin schubmult -- -m 1,3,4,2 2,1,4,5,3" "0+1*X[2,3,5,4,1]+1*X[4,1,5,2,3]+1*X[2,4,5,1,3]+1*X[3,2,4,5,1]+1*X[3,1,5,4,2]"

check "cargo run --bin schubmult -- -s 0,1,2,0,1,2 0,1,2,0,1,2" "1  (2,1,0,0,1,2)
1  (1,0,2,2,0,1)
1  (0,2,1,1,2,0)
1  (2,0,1,1,0,2)
1  (1,2,0,0,2,1)
1  (0,1,2,2,1,0)"

check "cargo run --bin schubmult -- -m -s 0,2,0,2,1,2 0,1,2,0,2,2" "0+1*X[0,2,1,2,2,0]+1*X[2,0,1,2,0,2]+1*X[2,0,2,0,1,2]+1*X[0,2,2,1,0,2]"

check "cargo run --bin allperms -- 0" "()"

check "cargo run --bin allperms -- 1" "(1)"

check "cargo run --bin allperms -- 3" "(1,2,3)
(1,3,2)
(2,1,3)
(2,3,1)
(3,1,2)
(3,2,1)"

exit $failed
