name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt, clippy
            override: true
      - name: Check format (main project)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Check format (helper project)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path lrcalc_helper/Cargo.toml -- --check
      - name: Check format (python project)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path python/Cargo.toml -- --check
      - name: Build
        run: |
          cargo build --verbose
          cargo build --manifest-path lrcalc_helper/Cargo.toml
          cargo build --manifest-path python/Cargo.toml
      - name: Run clippy (main project)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Run clippy (helper project)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path lrcalc_helper/Cargo.toml
      - name: Run clippy (python project)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path python/Cargo.toml
      - name: Run tests
        run: cargo test --verbose
      - name: Run testsuits
        run: ./testsuite
